# Generated by Django 4.1.3 on 2022-11-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, help_text='Please enter your given name', max_length=15, null=True, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, help_text='Please enter your middle name', max_length=15, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(blank=True, help_text='Please enter your last name', max_length=15, null=True, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, help_text='dd-mm-yyyy', null=True, verbose_name='Date of birth')),
                ('place_of_birth', models.CharField(blank=True, help_text='Citi where you were born', max_length=15, null=True)),
                ('city', models.CharField(blank=True, help_text='Please choose', max_length=15, null=True)),
                ('province', models.CharField(blank=True, help_text='Please choose', max_length=15, null=True)),
                ('street', models.CharField(blank=True, help_text='Please choose', max_length=30, null=True)),
                ('family_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Engaged', 'Engaged')], default='Single', max_length=8)),
                ('bg_personal_number', models.CharField(blank=True, help_text='EGN', max_length=15, null=True, verbose_name='EGN')),
                ('nationality', models.CharField(blank=True, help_text='Your nationality', max_length=15, null=True)),
                ('country_of_birth', models.CharField(blank=True, help_text='Which country you were born', max_length=15, null=True)),
                ('id_passport_number', models.CharField(blank=True, help_text='Document number', max_length=15, null=True)),
                ('passport_date_of_issue', models.DateField(blank=True, null=True)),
                ('is_received_visa', models.BooleanField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, help_text='Your phone number', max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('university', models.CharField(help_text='Your university', max_length=30)),
                ('year_of_education', models.PositiveIntegerField(blank=True, help_text='Курс', null=True)),
                ('foreign_university', models.CharField(blank=True, max_length=15, null=True)),
                ('is_fulltime_student', models.BooleanField(blank=True, null=True)),
                ('search_job_pref', models.CharField(blank=True, max_length=15, null=True)),
                ('how_to_reach', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
