# Generated by Django 4.1.3 on 2022-11-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(blank=True, help_text='Your university', max_length=30, null=True),
        ),
    ]
