# Generated by Django 4.1.3 on 2022-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_students_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bg_personal_number',
            field=models.CharField(blank=True, default='', help_text='EGN', max_length=15, null=True, verbose_name='EGN'),
        ),
        migrations.AlterField(
            model_name='students',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Please choose', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='country_of_birth',
            field=models.CharField(blank=True, default='', help_text='Which country you were born', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, default='', help_text='dd-mm-yyyy', null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Please enter your given name', max_length=15, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='foreign_university',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='how_to_reach',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_passport_number',
            field=models.CharField(blank=True, default='', help_text='Document number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_fulltime_student',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_received_visa',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Please enter your last name', max_length=15, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='Please enter your middle name', max_length=15, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='Your nationality', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Your phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', help_text='Citi where you were born', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='province',
            field=models.CharField(blank=True, default='', help_text='Please choose', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='search_job_pref',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='street',
            field=models.CharField(blank=True, default='', help_text='Please choose', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='university',
            field=models.CharField(blank=True, default='', help_text='Your university', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_of_education',
            field=models.PositiveIntegerField(blank=True, default='', help_text='Курс', null=True),
        ),
    ]
