# Generated by Django 4.1.3 on 2022-11-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_students_bg_personal_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='dd-mm-yyyy', null=True, verbose_name='Date of birth'),
        ),
    ]
