# Generated by Django 4.1.3 on 2022-11-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_students_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
