# Generated by Django 4.1.3 on 2022-11-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_students_passport_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='is_fulltime_student',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_received_visa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='year_of_education',
            field=models.PositiveIntegerField(blank=True, help_text='Курс', null=True),
        ),
    ]
