# Generated by Django 4.1.3 on 2022-11-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_students_is_fulltime_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='visa_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
