# Generated by Django 4.1.3 on 2022-11-28 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('user_profile', '0007_students_visa_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_role', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_pic', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
