# Generated by Django 4.1.3 on 2022-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='family_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('ENGAGED', 'Engaged'), ('OTHER', 'Other')], default='Single', max_length=8),
        ),
    ]
