# Generated by Django 4.1.3 on 2022-11-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_students_family_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='family_status',
        ),
    ]
