# Generated by Django 4.1.3 on 2022-11-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('job_position', models.CharField(max_length=30)),
                ('employer', models.CharField(blank=True, max_length=30, null=True)),
                ('sponsor', models.CharField(max_length=15)),
                ('wage', models.FloatField()),
            ],
        ),
    ]
