# Generated by Django 4.1.3 on 2022-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('job_position', models.CharField(max_length=30)),
                ('employer', models.CharField(blank=True, max_length=30, null=True)),
                ('sponsor', models.CharField(max_length=15)),
                ('wage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(blank=True, choices=[('Self Arranged', 'Self Arranged'), ('Full Placement Standard', 'Full Placement Standard'), ('Premium Full Placement', 'Premium Full Placement')], default='Full Placement Standard', max_length=25, null=True)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, help_text='Please enter description', null=True)),
            ],
        ),
    ]
