# Generated by Django 4.1.3 on 2022-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(blank=True, choices=[('Self Arranged', 'Self Arranged'), ('Full Placement Standard', 'Full Placement Standard'), ('Premium Full Placement', 'Premium Full Placement')], default='Full Placement Standard', max_length=25, null=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, help_text='Please enter description', null=True)),
            ],
        ),
    ]
