# Generated by Django 4.1.3 on 2022-11-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_joboffer_offer_pic_alter_joboffer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=30, null=True)),
                ('service_description', models.TextField(blank=True, null=True)),
                ('service_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='description',
            new_name='price_description',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='offer_pic',
            field=models.URLField(blank=True, null=True, verbose_name='Снимка-URL'),
        ),
    ]
